#!/bin/tcsh
#MSUB -l walltime=1:00:00
#MSUB -l nodes=64:ppn=2
#MSUB -o myjob.out128
#MSUB -j oe
#MSUB -V

##### These are shell commands
date

cd ${RUNS_DIR}

##### Strong Scaling
mpirun -np 128 -npersocket 1 ${BUILD_DIR}/clamr -n 1024 -i 100 -t 500 -P "hilbert_sort" -p "local_hilbert" -l 2 > ${RUNS_DIR}/strong_hilb_out128_2h_clamronly
mpirun -np 128 -npersocket 1 ${BUILD_DIR}/clamr -n 1024 -i 100 -t 500 -P "hilbert_sort" -p "local_hilbert" -l 4 > ${RUNS_DIR}/strong_hilb_out128_4h_clamronly

##### Strong Scaling
mpirun -np 128 -npersocket 1 ${BUILD_DIR}/clamr -n 1024 -i 100 -t 500 -P "original_order" -p "original_order" -l 2 > ${RUNS_DIR}/strong_orig_out128_2h_clamronly
mpirun -np 128 -npersocket 1 ${BUILD_DIR}/clamr -n 1024 -i 100 -t 500 -P "original_order" -p "original_order" -l 4 > ${RUNS_DIR}/strong_orig_out128_4h_clamronly

##### Weak Scaling
mpirun -np 128 -npersocket 1  ${BUILD_DIR}/clamr -n 5792 -i 100 -t 500 -P "hilbert_sort" -p "local_hilbert" -l 2 > ${RUNS_DIR}/weak_hilb_out128_2h_clamronly

##### Weak Scaling
mpirun -np 128 -npersocket 1  ${BUILD_DIR}/clamr -n 5792 -i 100 -t 500 -P "original_order" -p "original_order" -l 2 > ${RUNS_DIR}/weak_orig_out128_2h_clamronly

date
echo 'Done'

