#!/bin/tcsh
setenv BUILD_DIR `pwd`
setenv RUNS_DIR /scratch/brobey/test
setenv SCRIPTS_DIR `pwd`/moonlight_scripts

mkdir -p ${RUNS_DIR}
cd ${RUNS_DIR}

msub ${SCRIPTS_DIR}/msub001
msub ${SCRIPTS_DIR}/msub002
msub ${SCRIPTS_DIR}/msub004
msub ${SCRIPTS_DIR}/msub008
msub ${SCRIPTS_DIR}/msub016
msub ${SCRIPTS_DIR}/msub032
msub ${SCRIPTS_DIR}/msub064
msub ${SCRIPTS_DIR}/msub128
msub ${SCRIPTS_DIR}/msub256

msub ${SCRIPTS_DIR}/msub_mpi001
msub ${SCRIPTS_DIR}/msub_mpi002
msub ${SCRIPTS_DIR}/msub_mpi004
msub ${SCRIPTS_DIR}/msub_mpi008
msub ${SCRIPTS_DIR}/msub_mpi016
msub ${SCRIPTS_DIR}/msub_mpi032
msub ${SCRIPTS_DIR}/msub_mpi064
msub ${SCRIPTS_DIR}/msub_mpi128
msub ${SCRIPTS_DIR}/msub_mpi256
