#!/bin/tcsh
#MSUB -l walltime=0:30:00
#MSUB -l nodes=1:ppn=4
#MSUB -o myjob_mpi.out004
#MSUB -j oe
#MSUB -V

##### These are shell commands
date

cd ${RUNS_DIR}

##### Weak Scaling
mpirun -np 4  -npersocket 2  ${BUILD_DIR}/clamr_mpionly -n 1024  -i 100 -t 500 -P "hilbert_sort" -p "local_hilbert" -l 2 > ${RUNS_DIR}/weak_hilb_out004_2h_mpionly

##### Strong Scaling
mpirun -np 4  -npersocket 2 ${BUILD_DIR}/clamr_mpionly -n 1024 -i 100 -t 500 -P "hilbert_sort" -p "local_hilbert" -l 2 > ${RUNS_DIR}/strong_hilb_out004_2h_mpionly
mpirun -np 4  -npersocket 2 ${BUILD_DIR}/clamr_mpionly -n 1024 -i 100 -t 500 -P "hilbert_sort" -p "local_hilbert" -l 4 > ${RUNS_DIR}/strong_hilb_out004_4h_mpionly

##### Weak Scaling
mpirun -np 4  -npersocket 2  ${BUILD_DIR}/clamr_mpionly -n 1024  -i 100 -t 500 -P "original_order" -p "original_order" -l 2 > ${RUNS_DIR}/weak_orig_out004_2h_mpionly

##### Strong Scaling
mpirun -np 4  -npersocket 2 ${BUILD_DIR}/clamr_mpionly -n 1024 -i 100 -t 500 -P "original_order" -p "original_order" -l 2 > ${RUNS_DIR}/strong_orig_out004_2h_mpionly
mpirun -np 4  -npersocket 2 ${BUILD_DIR}/clamr_mpionly -n 1024 -i 100 -t 500 -P "original_order" -p "original_order" -l 4 > ${RUNS_DIR}/strong_orig_out004_4h_mpionly

date
echo 'Done'

