#!/bin/tcsh
#MSUB -l walltime=1:00:00
#MSUB -l nodes=128:ppn=2
#MSUB -o myjob.out256
#MSUB -j oe
#MSUB -V

##### These are shell commands
echo -n "JOBID: "
printenv SLURM_JOB_ID
echo -n "NUM_NODES: "
printenv SLURM_JOB_NUM_NODES
echo -n "NODES: "
printenv SLURM_NODELIST
date

cd ${RUNS_DIR}

##### Strong Scaling
mpirun -np 256 -npernode 2 ${BUILD_DIR}/clamr -n 1024 -i 100 -t 500 -P "hilbert_sort" -p "local_hilbert" -l 2 > ${RUNS_DIR}/strong_hilb_out256_2h_clamronly
mpirun -np 256 -npernode 2 ${BUILD_DIR}/clamr -n 1024 -i 100 -t 500 -P "hilbert_sort" -p "local_hilbert" -l 4 > ${RUNS_DIR}/strong_hilb_out256_4h_clamronly

##### Strong Scaling
mpirun -np 256 -npernode 2 ${BUILD_DIR}/clamr -n 1024 -i 100 -t 500 -P "original_order" -p "original_order" -l 2 > ${RUNS_DIR}/strong_orig_out256_2h_clamronly
mpirun -np 256 -npernode 2 ${BUILD_DIR}/clamr -n 1024 -i 100 -t 500 -P "original_order" -p "original_order" -l 4 > ${RUNS_DIR}/strong_orig_out256_4h_clamronly

##### Weak Scaling
mpirun -np 256 -npernode 2  ${BUILD_DIR}/clamr -n 8192 -i 100 -t 500 -P "hilbert_sort" -p "local_hilbert" -l 2 > ${RUNS_DIR}/weak_hilb_out256_2h_clamronly
mpirun -np 256 -npernode 2  ${BUILD_DIR}/clamr -n 8192 -i 100 -t 500 -P "hilbert_sort" -p "local_hilbert" -l 4 > ${RUNS_DIR}/weak_hilb_out256_4h_clamronly

##### Weak Scaling
mpirun -np 256 -npernode 2  ${BUILD_DIR}/clamr -n 8192 -i 100 -t 500 -P "original_order" -p "original_order" -l 2 > ${RUNS_DIR}/weak_orig_out256_2h_clamronly
mpirun -np 256 -npernode 2  ${BUILD_DIR}/clamr -n 8192 -i 100 -t 500 -P "original_order" -p "original_order" -l 4 > ${RUNS_DIR}/weak_orig_out256_4h_clamronly

date
echo 'Done'

