#!/bin/tcsh
#MSUB -l walltime=2:00:00
#MSUB -l nodes=1:ppn=1
#MSUB -o myjob.out001
#MSUB -j oe
#MSUB -V

##### These are shell commands
echo -n "JOBID: "
printenv SLURM_JOB_ID
echo -n "NUM_NODES: "
printenv SLURM_JOB_NUM_NODES
echo -n "NODES: "
printenv SLURM_NODELIST
date

cd ${RUNS_DIR}

##### Strong Scaling
${BUILD_DIR}/clamr_gpuonly -n 1024 -i 100 -t 500 -P "hilbert_sort" -p "local_hilbert" -l 2 > ${RUNS_DIR}/strong_hilb_out001_2h_gpuonly
${BUILD_DIR}/clamr_gpuonly -n 1024 -i 100 -t 500 -P "hilbert_sort" -p "local_hilbert" -l 4 > ${RUNS_DIR}/strong_hilb_out001_4h_gpuonly

##### Strong Scaling
${BUILD_DIR}/clamr_cpuonly -n 1024 -i 100 -t 500 -P "hilbert_sort" -p "local_hilbert" -l 2 > ${RUNS_DIR}/strong_hilb_out001_2h_cpuonly
${BUILD_DIR}/clamr_cpuonly -n 1024 -i 100 -t 500 -P "hilbert_sort" -p "local_hilbert" -l 4 > ${RUNS_DIR}/strong_hilb_out001_4h_cpuonly

##### Strong Scaling
${BUILD_DIR}/clamr_gpuonly -n 1024 -i 100 -t 500 -P "original_order" -p "original_order" -l 2 > ${RUNS_DIR}/strong_orig_out001_2h_gpuonly
${BUILD_DIR}/clamr_gpuonly -n 1024 -i 100 -t 500 -P "original_order" -p "original_order" -l 4 > ${RUNS_DIR}/strong_orig_out001_4h_gpuonly

##### Strong Scaling
${BUILD_DIR}/clamr_cpuonly -n 1024 -i 100 -t 500 -P "original_order" -p "original_order" -l 2 > ${RUNS_DIR}/strong_orig_out001_2h_cpuonly
${BUILD_DIR}/clamr_cpuonly -n 1024 -i 100 -t 500 -P "original_order" -p "original_order" -l 4 > ${RUNS_DIR}/strong_orig_out001_4h_cpuonly

date
echo 'Done'

