#!/bin/tcsh
#MSUB -l walltime=1:00:00
#MSUB -l nodes=4:ppn=8
#MSUB -o myjob_mpi.out032
#MSUB -j oe
#MSUB -V

##### These are shell commands
echo -n "JOBID: "
printenv SLURM_JOB_ID
echo -n "NUM_NODES: "
printenv SLURM_JOB_NUM_NODES
echo -n "NODES: "
printenv SLURM_NODELIST
date

cd ${RUNS_DIR}

##### Weak Scaling
mpirun -np 32 -npernode 8  ${BUILD_DIR}/clamr_mpionly -n 2896 -i 100 -t 500 -P "hilbert_sort" -p "local_hilbert" -l 2 > ${RUNS_DIR}/weak_hilb_out032_2h_mpionly
mpirun -np 32 -npernode 8  ${BUILD_DIR}/clamr_mpionly -n 2896 -i 100 -t 500 -P "hilbert_sort" -p "local_hilbert" -l 4 > ${RUNS_DIR}/weak_hilb_out032_4h_mpionly

##### Strong Scaling
mpirun -np 32 -npernode 8 ${BUILD_DIR}/clamr_mpionly -n 1024 -i 100 -t 500 -P "hilbert_sort" -p "local_hilbert" -l 2 > ${RUNS_DIR}/strong_hilb_out032_2h_mpionly
mpirun -np 32 -npernode 8 ${BUILD_DIR}/clamr_mpionly -n 1024 -i 100 -t 500 -P "hilbert_sort" -p "local_hilbert" -l 4 > ${RUNS_DIR}/strong_hilb_out032_4h_mpionly

##### Weak Scaling
mpirun -np 32 -npernode 8  ${BUILD_DIR}/clamr_mpionly -n 2896 -i 100 -t 500 -P "original_order" -p "original_order" -l 2 > ${RUNS_DIR}/weak_orig_out032_2h_mpionly
mpirun -np 32 -npernode 8  ${BUILD_DIR}/clamr_mpionly -n 2896 -i 100 -t 500 -P "original_order" -p "original_order" -l 4 > ${RUNS_DIR}/weak_orig_out032_4h_mpionly

##### Strong Scaling
mpirun -np 32 -npernode 8 ${BUILD_DIR}/clamr_mpionly -n 1024 -i 100 -t 500 -P "original_order" -p "original_order" -l 2 > ${RUNS_DIR}/strong_orig_out032_2h_mpionly
mpirun -np 32 -npernode 8 ${BUILD_DIR}/clamr_mpionly -n 1024 -i 100 -t 500 -P "original_order" -p "original_order" -l 4 > ${RUNS_DIR}/strong_orig_out032_4h_mpionly

date
echo 'Done'

